### ISSUE TITLE
Cannot choose any other hard drive than C:

### ISSUE THREAD

**Issue by nfuryn** [daattali/shinyfilebrowser#7]
Basically it. The "back" button does not go further back, clicking on C: also does not do anything.

**Comment by daattali** [comment]
If you specify the `path` argument to a location in a different drive, does it work?

**Comment by nfuryn** [comment]
yes, it does

**Comment by daattali** [comment]
Ok that's at least good, that would have bee a big problem. I'll try to look into this a bit, but it may not be fixed

**Comment by nfuryn** [comment]
maybe shinyFiles could be a source of inspiration, there it does go back as far as possible as long as you specify:
  volumes <- c(Home = fs::path_home(), "R Installation" = R.home(), getVolumes()())
  shinyFileChoose(input, "file", roots = volumes, session = session)

**Comment by daattali** [comment]
I added a compromise between what you want and what I could do without making the code unmaintainable. You cannot browse to "My Computer" to select different drives, but I added a `get_drives()` function, and I showed an example in its documentation of how you can use it to browse different drives. Here's a basic example:

```r
library(shiny)

ui <- fluidPage(
  selectInput("drive", "Select drive", get_drives()),
  file_browser_ui("files")
)

server <- function(input, output, session) {
  path <- reactive({
    if (input$drive == "C:/") {
      "~"
    } else {
      input$drive
    }
  })
  file_browser_server("files", path = path, root = reactive(input$drive))
}

shinyApp(ui, server)
```

I understand this might not be the solution you wanted, but I've been thinking a lot about this and even started implementing it, and unfortunately I think this is the best I can do on Windows because of how weird Windows is. If I **HAD** to get a file browser that allows me to navigate to different drives and it was needed to be used in one application, then I could implement that. But I'm trying to keep the code here clean and easy to maintain and generalizable, and I would have had to add hacky workarounds in too many places to accommodate this, so I decided against it.

**Comment by nfuryn** [comment]
This look great, thank you! Some might argue that this is even a superior solution since you don't have to click back many times to get to "my computer" :)
Fyi though your if statement was giving me "Error in if: argument is of length zero" so I had to change it:
```
path <- reactive({
    if (length(input$drive) == 0) {
      return("~")
    } else {
      return(input$drive)
    }
  })
```

**Comment by daattali** [comment]
1. You may not have realized this "hidden" feature, but you don't have to click "back" many times. The breadcrumbs at the top are clickable, so you can just click on any folder in the breadcrumbs to go there directly (assuming it's not below the given root)

2. The code I gave should work on windows. If it's erroring for you on windows then do let me know as that's a bug I'll need to fix. The code you modified wouldn't really do what I intended for it to do: if I selwcr C drive then I want tye default path to be the home dir, if I select any other drive then rhe default path should start at that drive's root

**Comment by daattali** [comment]
I've updated the `get_drives()` function to return `"/"` on non-windows machines, so it can work nicely on any machine. But it is meant to be used only when you're on windows.

**Comment by nfuryn** [comment]
Well yes, it is erroring with your code
"Warning: Error in if: argument is of length zero"

**Comment by daattali** [comment]
The latest version is erroring?
